steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/librarian/librarian-service:$COMMIT_SHA', '.']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/librarian/librarian-service:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'librarian-service'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/librarian/librarian-service:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'GOOGLE_API_KEY=$$GOOGLE_API_KEY' # Pass the secret
      - '--quiet'
# This allows the build to access the secret
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/GOOGLE_API_KEY/versions/latest
      env: 'GOOGLE_API_KEY'
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/librarian/librarian-service:$COMMIT_SHA' 