steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/librarian/librarian-service:$BUILD_ID', '.']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/librarian/librarian-service:$BUILD_ID']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'librarian-service'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/librarian/librarian-service:$BUILD_ID'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-secrets=GOOGLE_API_KEY=GOOGLE_API_KEY:latest'
      - '--quiet'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/librarian/librarian-service:$BUILD_ID' 